CREATE DATABASE money_app;

CREATE TABLE user (
	id INT(10) NOT NULL AUTO_INCREMENT,
	nama VARCHAR(100) NOT NULL COLLATE 'utf8mb4_0900_ai_ci',
	email VARCHAR(100) NOT NULL COLLATE 'utf8mb4_0900_ai_ci',
	password VARCHAR(255) NOT NULL COLLATE 'utf8mb4_0900_ai_ci',
	phone VARCHAR(15) NULL DEFAULT NULL COLLATE 'utf8mb4_0900_ai_ci',
	foto VARCHAR(255) NULL DEFAULT 'uploads/default.png' COLLATE 'utf8mb4_0900_ai_ci',
	created_at TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
	role ENUM('admin','user') NOT NULL DEFAULT 'user' COLLATE 'utf8mb4_0900_ai_ci',
	reset_token VARCHAR(255) NULL DEFAULT NULL COLLATE 'utf8mb4_0900_ai_ci',
	reset_token_expire DATETIME NULL DEFAULT NULL,
	updated_at TIMESTAMP NULL DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP,
	PRIMARY KEY (id) USING BTREE,
	UNIQUE INDEX email (email) USING BTREE,
	UNIQUE INDEX phone (phone) USING BTREE
)
COLLATE='utf8mb4_0900_ai_ci'
ENGINE=InnoDB
AUTO_INCREMENT=10
;


CREATE TABLE batas_pengeluaran (
	id INT(10) NOT NULL AUTO_INCREMENT,
	kategori VARCHAR(100) NOT NULL COLLATE 'utf8mb4_0900_ai_ci',
	batas INT(10) NOT NULL,
	user_id INT(10) NULL DEFAULT NULL,
	PRIMARY KEY (id) USING BTREE
)
COLLATE='utf8mb4_0900_ai_ci'
ENGINE=InnoDB
;

CREATE TABLE kategori_batas (
	id INT(10) NOT NULL AUTO_INCREMENT,
	nama_kategori VARCHAR(100) NOT NULL COLLATE 'utf8mb4_0900_ai_ci',
	batas INT(10) NOT NULL,
	user_id INT(10) NULL DEFAULT NULL,
	PRIMARY KEY (id) USING BTREE,
	UNIQUE INDEX nama_kategori (nama_kategori) USING BTREE
)
COLLATE='utf8mb4_0900_ai_ci'
ENGINE=InnoDB
AUTO_INCREMENT=3
;

CREATE TABLE transaksi (
	id INT(10) NOT NULL AUTO_INCREMENT,
	tanggal DATE NOT NULL,
	nominal INT(10) NOT NULL,
	kategori VARCHAR(100) NULL DEFAULT NULL COLLATE 'utf8mb4_0900_ai_ci',
	user_id INT(10) NULL DEFAULT NULL,
	PRIMARY KEY (id) USING BTREE,
	INDEX user_id (user_id) USING BTREE,
	CONSTRAINT transaksi_ibfk_1 FOREIGN KEY (user_id) REFERENCES user (id) ON UPDATE NO ACTION ON DELETE NO ACTION
)
COLLATE='utf8mb4_0900_ai_ci'
ENGINE=InnoDB
;

CREATE TABLE uang_keluar (
	id INT(10) NOT NULL AUTO_INCREMENT,
	nominal INT(10) NULL DEFAULT NULL,
	tanggal DATE NULL DEFAULT NULL,
	kategori VARCHAR(50) NULL DEFAULT NULL COLLATE 'utf8mb4_0900_ai_ci',
	keterangan TEXT NULL DEFAULT NULL COLLATE 'utf8mb4_0900_ai_ci',
	user_id INT(10) NULL DEFAULT NULL,
	PRIMARY KEY (id) USING BTREE
)
COLLATE='utf8mb4_0900_ai_ci'
ENGINE=InnoDB
AUTO_INCREMENT=8
;

CREATE TABLE uang_masuk (
	id INT(10) NOT NULL AUTO_INCREMENT,
	nominal INT(10) NULL DEFAULT NULL,
	tanggal DATE NULL DEFAULT NULL,
	kategori VARCHAR(50) NULL DEFAULT NULL COLLATE 'utf8mb4_0900_ai_ci',
	keterangan TEXT NULL DEFAULT NULL COLLATE 'utf8mb4_0900_ai_ci',
	user_id INT(10) NULL DEFAULT NULL,
	PRIMARY KEY (id) USING BTREE
)
COLLATE='utf8mb4_0900_ai_ci'
ENGINE=InnoDB
AUTO_INCREMENT=15
;

